#pragma once

namespace ast {

// Program
class AbstractDeclarator;
class ArrayDirectAbstractDeclarator;
class ArrayDirectDeclarator;
class BasicKeywordSpecifier;
class Declaration;
class DeclarationList;
class DeclarationSpecifiers;
class Declarator;
class DirectAbstractDeclarator;
class DirectDeclarator;
class Enumerator;
class EnumeratorList;
class EnumSpecifier;
class ExternalDeclaration;
class FunctionDefinition;
class IdentDeclarationSpecifiers;
class IdentDirectDeclarator;
class IdentSpecifier;
class InitDeclarator;
class InitDeclaratorList;
class Initializer;
class InitializerList;
class KeywordDeclarationSpecifiers;
class KeywordSpecifier;
class NestedDirectAbstractDeclarator;
class NestedDirectDeclarator;
class ParameterDeclaration;
class ParameterDirectAbstractDeclarator;
class ParameterDirectDeclarator;
class ParameterList;
class ParameterTypeList;
class Pointer;
class Specifier;
class SpecifierQualifierList;
class StorageClassSpecifier;
class StructDeclaration;
class StructDeclarationList;
class StructDeclarator;
class StructDeclaratorList;
class StructOrUnionSpecifier;
class TranslationUnit;
class TypeName;
class TypeQualifier;
class TypeQualifierList;


// Expression
class AccessExpression;
class AdditiveExpression;
class AndExpression;
class ArgumentExpressionList;
class AssignmentExpression;
class AssignmentOperator;
class CallExpression;
class CastExpression;
class CastTypenameExpression;
class CastUnaryExpression;
class ConditionalAssignmentExpression;
class ConditionalExpression;
class ConstantExpression;
class EqualityExpression;
class ExclusiveOrExpression;
class Expression;
class IdentPrimaryExpression;
class IncDecPostfixExpression;
class IncDecPrefixExpression;
class InclusiveOrExpression;
class IndexExpression;
class LogicalAndExpression;
class LogicalOrExpression;
class MultiplicativeExpression;
class NestedPrimaryExpression;
class NumberPrimaryExpression;
class OperatorUnaryExpression;
class PostfixExpression;
class PrefixExpression;
class PrimaryExpression;
class RelationalExpression;
class ShiftExpression;
class SizeofTypenameExpression;
class SizeofUnaryExpression;
class UnaryAssignExpression;
class UnaryExpression;
class UnaryOperator;


// Statement
class CaseLabeledStatement;
class CompoundStatement;
class DefaultLabeledStatement;
class DoWhileIterationStatement;
class ExpressionStatement;
class ForIterationStatement;
class IdentLabeledStatement;
class IfSelectionStatement;
class IterationStatement;
class JumpStatement;
class LabeledStatement;
class LoopJumpStatement;
class ReturnJumpStatement;
class SelectionStatement;
class Statement;
class StatementList;
class SwitchSelectionStatement;
class WhileIterationStatement;

}  // namespace ast
